pipeline:
  build:
    image: alpine:latest
    commands:
      - sh patch.sh
    

matrix:
  what_to_patch:
    - youtube
    - youtube-music
    - reddit
    - twitch
    - twitter
    - spotify
    - tiktok
